### ISSUE TITLE
Find basic asset store synth

### ISSUE THREAD

**Issue by unoctium1** [ubcemergingmedialab/SynesthesiAR#1]
We should find a basic piano/synth for testing purposes

**Comment by unoctium1** [comment]
Use MRTK keyboard

**Comment by unoctium1** [comment]
The main focus now should just be to set up a scene in Unity with the keyboard or several instances of it around the room

**Comment by allen6chen** [comment]
Spatial music disturbance occurs when user rotates and move the camera in the Unity Editor Scene (not sure about in the Hololens)
